# pylint: disable = redefined-outer-name
# pylint: disable = unused-argument
# pylint: disable = line-too-long
# pylint: disable = expression-not-assigned

'''Calculator Test'''
from decimal import Decimal
import pytest
from calculator import Calculator
from calculator.operations import Operation

def test_operations(a, b, operation, expected):
    '''Tests various operations using data generated by Faker'''
    assert Calculator.execute(a, b, operation) == expected, f'{operation.__name__} operation failed'

def test_division_by_zero():
    '''Tests that divide by zero exception'''
    with pytest.raises(ValueError, match = 'Cannot divide by zero!'):
        Calculator.execute(Decimal('2'), Decimal('0'), Operation.divide), 'Divide by Zero exception failed'

@pytest.fixture
def setup_history():
    '''Clears history and adds sample calculations for tests'''
    Calculator.clear_history()
    Calculator.execute(Decimal('2'), Decimal('2'), Operation.add)
    Calculator.execute(Decimal('2'), Decimal('2'), Operation.subtract)

def test_history(setup_history):
    '''Tests that history show previous, show history, and clear history functions work'''
    assert Calculator.show_history() == [(2, 2, 'add'), (2, 2, 'subtract')], 'Failed to retrieve history!'
    assert Calculator.show_previous() == (2, 2, 'subtract'), 'Failed to retrieve previous log'
    Calculator.clear_history()
    assert Calculator.show_previous() == 'No History!', 'Failed to clear history and/or show no previous history!'
    assert Calculator.show_history() == 'No History!', 'Failed to clear and/or show no history!'
