# pylint: disable = expression-not-assigned

'''Calculation Test'''
from decimal import Decimal
import pytest
from calculator.calculation import Calculation
from calculator.operations import Operation

def test_calculation_operations2(a, b, operation, expected):
    '''Tests various operations using data generated by Faker'''
    calc = Calculation(a, b, operation)
    assert calc.compute() == expected, f'{operation.__name__} operation failed'

def test_division_by_zero():
    '''Tests that divide by zero exception'''
    calc = Calculation(Decimal('2'), Decimal('0'), Operation.divide)
    with pytest.raises(ValueError, match = 'Cannot divide by zero!'):
        calc.compute(), 'Divide by Zero exception failed'
